blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/rsainju/autorag-live/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/rsainju/autorag-live/tree/main/docs
    about: Check the comprehensive documentation
  - name: 🔒 Security Issue
    url: https://github.com/rsainju/autorag-live/security/advisories/new
    about: Report a security vulnerability privately
