# @package _group_
default:
  hard_negatives:
    sampling_strategy: random
    num_samples: 5
    min_score_diff: 0.2
    
  query_rewrites:
    num_variations: 3
    diversity_penalty: 0.1
    max_length: 100
    
  synonym_mining:
    min_similarity: 0.7
    max_synonyms: 5
    update_threshold: 0.8